name: "Send Sendgrid Email"
description: "Send an email using Sendgrid"
inputs:
  from:
    description: "The email address of the sender"
    required: true
  to:
    description: "The email address of the recipient"
    required: true
  subject:
    description: "The subject of the email"
    required: true
  body_text:
    description: "The body of the email in text format"
    required: false
  body_html:
    description: "The body of the email in HTML format"
    required: false
  sendgrid_api_key:
    description: "The Sendgrid API key, may also be passed via env: SENDGRID_API_KEY"
    required: true
outputs:
  status:
    description: "The status code returned by the Sendgrid API"
runs: 
  using: "node20"
  main: "index.js"
